# Enable Flutter-specific lint rules
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Aktifkan atau nonaktifkan aturan lint tambahan di bawah ini sesuai kebutuhan

    # Contoh:
    avoid_print: true               # Hindari penggunaan print, gunakan debugPrint/log
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
