name: visual_expense_tracker
description: A Flutter app to track expenses using camera, OCR, geolocation, and data analysis.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  image_picker: ^1.0.4
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^11.0.0
  camera: ^0.10.5+5
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.0
  intl: ^0.18.1

  # Plugin OCR versi lokal
  google_mlkit_text_recognition:
    path: mlkit_plugins/google_mlkit_text_recognition

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

