name: google_mlkit_commons
description: Common utilities for Google ML Kit Flutter plugins.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
